### ISSUE TITLE
" char highlights strings

### ISSUE THREAD

**Issue by ghost** [eneerge/mIRC-Scripting-Language-for-Sublime-Text#2]
Everything between double quote marks `"` is highlighted in yellow. 

A single `"` char contained in brackets in an if-clause erroneously marks the start of a string:

File: first.mrc - Line: 1523
![image](https://user-images.githubusercontent.com/13683523/37697440-36291d26-2cdd-11e8-9e06-6b988a8a9df5.png)

I tried your `\s` trick that resolved issue #1 but doing that doesn't match the following:

![image](https://user-images.githubusercontent.com/13683523/37697714-a98c0020-2cde-11e8-9b24-49e69f4825b7.png)

Thanks for your time and effort :)

**Comment by eneerge** [comment]
The issue here is what the detection of popup strings.  I've placed some additional checks for the $?!= sequence and moved the string detection before the operator check.  This has the slight disadvantage of not highlighting $?!=, but shouldn't break highlighting when " appears.  

There should be another way to fix the popup operator sequence and I'll look at that later when I have a little more time.
